[package]
name = "api-server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mongodb = "2.3.1"
serde = "1.0.145"
serde_json = "1.0.86"
tokio = "1.21.2"
warp = "0.3.3"
